// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouTubePlays.Discord.Bot.EntityFramework;

namespace YouTubePlays.Discord.Bot.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("YouTubePlays.Discord.Bot.EntityFramework.Table.ChannelSettings", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyboardType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TouchAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TouchXOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TouchYOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.ToTable("ChannelSettingsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
